// <auto-generated />
// ReSharper disable InconsistentNaming
#pragma warning disable 169

namespace RedBadger.CloudFolderBackup.Specs
{
    using Machine.Specifications;

    [Subject(typeof(IFolderConnection))]
    public class when_initialised_with_a_valid_path
    {
        protected static IFolderConnection folderConnection;

        private Establish context = () => folderConnection = new FolderConnection(@"C:\Windows");

        private It should_be_valid = () => folderConnection.IsValid().ShouldBeTrue();
    }

    [Subject(typeof(IFolderConnection))]
    public class when_initialised_with_an_invalid_path
    {
        protected static IFolderConnection folderConnection;

        private Establish context = () => folderConnection = new FolderConnection(@"C:\ThisFolderShouldNeverExxxist");

        private It should_be_valid = () => folderConnection.IsValid().ShouldBeFalse();
    }
}